### ISSUE TITLE
Compatibility with Vitis-AI v1.3

### ISSUE THREAD

**Issue by nimaomidsajedi** [beetleboxorg/sign_language_mnist#3]
Hi,
First of all, let me thank you for the amazing job of implementing a NN on MPSoC. As I see, your project runs on Vitis-AI v1.2; Is it possible for you to give an update so it can be compatible with Vitis-AI v1.3? 
I tried to do some modifications so I can run your project on v1.3 but I was unsuccessful and I cannot generate the *.elf file... For example, as you know, from v1.3, DPU on the ZCU platform uses XIR based compiler. I already noticed this but I had no luck running your project on the ZCU102 board.

**Comment by AndrewSwirski** [comment]
Updated to Vitis AI 1.4
